### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by alelordelo** [ClusterDB/RChat#2]
Hi Andrew,

Is there a companion tutorial for this? Or just a basic setup on how to config server and build?

**Comment by am-MongoDB** [comment]
I'm working on an article and then the README files this week. But, it's pretty simple – import the Realm app then set the app id in RChatApp.swift and then build

**Comment by alelordelo** [comment]
ok, cool. SO basically follow the same Server setup from Task Tutorial right? thanks for helping, will give it a go!

**Comment by alelordelo** [comment]
When trying to impiety the app, I am getting an error that "could not find realm app".:

alexandrelordelo@Alexandres-iPro RChat % cd /Users/alexandrelordelo/RChat/RChat-Realm/RChat
alexandrelordelo@Alexandres-iPro RChat % realm-cli import
could not find realm app

I noted that there is no config file like on Task App:
/RChat/RChat-Realm

Should be one? or this is auto generated after the import?

**Comment by am-MongoDB** [comment]
The config file should be there. I've just merged an updated version of the Realm app and added instructions to the README.

**Comment by am-MongoDB** [comment]
The tutorial is now live at https://developer.mongodb.com/how-to/building-a-mobile-chat-app-using-realm/
